'use strict';
(async()=>{
  const iframe=document.getElementById('test-game'),results=document.getElementById('test-results');
  const lines=[];let passed=0;
  function assert(ok,message){const line=(ok?'PASS ':'FAIL ')+message;lines.push(line);results.textContent=lines.join('\n');console[ok?'info':'error'](line);if(!ok)throw new Error(message);passed++;}
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  try{
    const start=performance.now();while(!iframe.contentWindow.verdantWorld){if(performance.now()-start>95000)throw new Error('Initialization timed out');await wait(100);}
    const w=iframe.contentWindow,d=w.document,game=w.verdantWorld,x=game.expansion,t=x.test,s=()=>x.getState();
    assert(s().enemies.filter(e=>e.type==='goblin').length===6,'Six goblins exist in the live scene');
    assert(s().enemies.filter(e=>e.type==='creatures').length===8,'Eight distinct human Creatures exist');
    assert(x.interact()===false,'Boarding is rejected when not near a vehicle');
    t.clearEnemies();let p=s().car;t.teleport(p.x+2,p.z);assert(x.interact()&&s().mode==='car','Board a nearby car');
    let z=game.getState().position.z;t.drive(1,{mx:0,mz:-1,running:false});assert(s().vehicleSpeed>10&&game.getState().position.z<z,'Car accelerates and moves across terrain');
    assert(!x.interact()&&s().mode==='car','Cannot exit a moving car');
    t.drive(5,{mx:0,mz:0,running:false});assert(x.interact()&&s().mode==='foot','Friction stops the car and permits exiting');
    p=s().plane;t.teleport(p.x+3,p.z);assert(x.interact()&&s().mode==='plane','Board the actual aircraft');
    t.holdAscend(true);t.drive(4,{mx:0,mz:-1,running:false});t.holdAscend(false);
    assert(s().altitude>5&&s().vehicleSpeed>20,'Aircraft accelerates, takes off and gains altitude');
    assert(!x.interact(),'Exiting the aircraft in flight is blocked');
    t.holdDescend(true);t.drive(6,{mx:0,mz:1,running:false});t.holdDescend(false);
    assert(s().altitude<.1&&s().vehicleSpeed<3,'Aircraft descends, lands and brakes');
    assert(x.interact()&&s().mode==='foot','Exit a landed aircraft');
    t.teleport(0,62);x.spawnGroup('goblin',true);assert(s().enemies.length===6,'A real goblin ambush is spawned');
    let before=Math.hypot(s().enemies[0].x,s().enemies[0].z-62);t.step(1);let after=Math.hypot(s().enemies[0].x,s().enemies[0].z-62);assert(after<before,'Goblins actively chase the player');
    assert(x.attack()&&s().projectiles>0,'Attack creates a visible ranged projectile');
    t.step(.7);assert(s().enemies.some(e=>e.hp<65),'Projectile collision damages an actual goblin');
    p=s().enemies[0];t.teleport(p.x,p.z+1);t.step(2.2);assert(s().hp<100,'Enemy attack telegraph resolves and reduces player HP');
    let health=s().hp;t.hurt(20);assert(s().hp<health,'Damage and player HP are connected');
    assert(x.heal()&&s().potions===2,'Healing restores HP and consumes a potion');
    assert(x.dodge(),'Dodge grants temporary evasion');health=s().hp;assert(!t.receiveDamage(20)&&s().hp===health,'Dodge invulnerability prevents actual incoming damage');
    t.clearEnemies();t.teleport(0,62);assert(x.startBoss(),'Boss encounter starts');
    assert(s().boss.hp===900&&s().weather==='storm','Boss has 900 HP and triggers a storm');
    t.hitNearest(470);t.step(.05);assert(s().boss.phase===2,'Boss enters phase II below half HP');
    t.hitNearest(1000);assert(s().boss.dead&&s().bossWins===1,'Boss can be defeated and victory is recorded');
    assert(d.getElementById('boss-hud').hidden,'Boss bar hides on victory');
    t.clearEnemies();t.teleport(0,62);x.spawnGroup('creatures',true);assert(s().enemies.length===8&&s().enemies.every(e=>e.aggro),'Creatures attack as an eight-person squad');
    const pos=s().enemies[0].x;x.update(1,true);assert(s().enemies[0].x===pos,'Paused dialogs freeze enemy simulation');
    for(const type of ['rain','fog','clear']){assert(x.setWeather(type)&&s().weather===type,'Weather can change to '+type);}
    x.setWeather('storm');t.step(3);assert(s().weatherIntensity>.4,'Weather appearance blends gradually rather than switching a label only');
    t.clearEnemies();t.hurt(1000);assert(s().dead&&d.getElementById('defeat-dialog').open,'Lethal damage opens the defeat screen');
    assert(!x.attack(),'Defeated player cannot attack');x.respawn();assert(!s().dead&&s().hp===100&&s().potions===3,'Respawn restores health and potions');
    assert(!d.getElementById('defeat-dialog').open,'Respawn closes defeat dialog');
    d.getElementById('events-button').click();assert(d.getElementById('events-dialog').open&&game.getState().paused,'Event board opens and pauses the game');
    d.querySelector('[data-weather="clear"]').click();await wait(200);assert(!game.getState().paused&&s().weather==='clear','Weather button executes its action and resumes play');
    t.clearEnemies();t.teleport(0,62);x.spawnGroup('creatures',true);t.hurt(1000);x.respawn();assert(s().enemies.every(e=>Math.hypot(e.x,e.z-62)>65),'Respawn relocates nearby ambushers away from the base');
    const save=localStorage.getItem('verdant-wildfront-v2');w.dispatchEvent(new w.Event('pagehide'));assert(localStorage.getItem('verdant-wildfront-v2')===save,'Self-test does not overwrite Wildfront save data');
    // Sensory gameplay regression: use production actions and deterministic simulation time.
    t.clearEnemies();x.respawn();t.step(3);
    assert(d.body.classList.contains('immersive'),'Quiet icon-first interface is the default');
    assert(w.getComputedStyle(d.querySelector('.journey-panel')).display==='none','Exploration prose is absent from the play surface');
    assert(x.attack()&&s().combo===1&&s().stamina===92,'First strike starts a combo and consumes stamina');
    t.step(.35);assert(x.attack()&&s().combo===2,'Second timed strike advances the combo');
    t.step(.35);assert(x.attack()&&s().combo===3,'Third timed strike activates the finisher');
    t.step(1.5);assert(s().combo===0,'Idle time resets combo progress');
    t.setStamina(0);assert(!x.attack()&&!x.dodge(),'Exhausted player cannot attack or dodge');
    t.step(4);assert(s().stamina===100,'Stamina regenerates to its bounded maximum');
    x.prepareMove(1,{mx:0,mz:-1,running:true});assert(s().stamina===82,'Sprinting consumes stamina through actual movement input');
    t.setStamina(100);const oldX=game.getState().position.x;
    x.prepareMove(.01,{mx:1,mz:0,running:false});assert(x.dodge(),'Directional dodge can start');t.step(.3);
    assert(game.getState().position.x>oldX+5,'Dodge travels in the requested movement direction');
    t.step(1);x.pauseInputs();const oldZ=game.getState().position.z;x.dodge();t.step(.3);
    assert(game.getState().position.z>oldZ+5,'Idle dodge retreats instead of always lunging forward');
    t.step(2);t.beginAttack();t.step(.7);assert(s().chargeTime>=.65,'Holding attack reaches the charged threshold');
    t.releaseAttack();assert(s().attackCD>.6&&s().stamina<=68,'Releasing charged attack spends its larger resource cost');
    t.step(2);x.attack();t.step(.2);assert(!x.attack(),'A near-ready attack is buffered rather than fired twice');t.step(.15);
    assert(s().combo===2,'Buffered attack executes once cooldown completes');
    t.step(2);t.beginAttack();t.step(.4);x.pauseInputs();t.releaseAttack();
    assert(s().chargeTime===0&&s().attackCD===0,'Pausing cancels held charge without an accidental attack');
    assert(x.sense()&&s().senseTime>0&&!x.sense(),'Wind guidance activates and enforces its cooldown');
    const frozen=s();x.update(1,true);assert(s().senseTime===frozen.senseTime&&s().stamina===frozen.stamina,'Pause freezes guidance and stamina simulation');
    t.clearEnemies();x.respawn();t.teleport(0,62);x.startBoss();p=s().enemies.find(e=>e.type==='boss');t.teleport(p.x,p.z+2);t.setWindup(.2);
    assert(x.dodge()&&s().focusTime>1&&s().empowered>0&&s().perfectDodges>0,'Last-moment dodge creates a slow-motion counter window');
    const windup=s().enemies[0].windup;t.step(.1);assert(s().enemies[0].windup>windup-.04,'Perfect evasion actually slows enemy attack timing');
    x.attack();assert(s().empowered===0,'Counter enhancement is consumed by the next strike');
    t.step(.8);t.hitNearest(1000);const drops=s().pickups;assert(drops>0,'Defeated enemies leave collectible recovery light');
    const oldCollected=s().collected;t.teleport(p.x,p.z);t.step(.2);assert(s().collected>oldCollected,'Approaching recovery light collects it');
    t.clearEnemies();x.respawn();t.step(1);t.beginAttack();t.step(.3);w.dispatchEvent(new w.Event('blur'));t.releaseAttack();
    assert(s().chargeTime===0&&s().attackCD===0,'Window blur safely cancels held attacks');
    d.getElementById('settings-button').click();d.getElementById('controls-guide').click();await wait(150);
    assert(d.getElementById('guide-dialog').open&&game.getState().paused,'Opening the guide from settings keeps simulation paused');
    d.getElementById('guide-dialog').close();await wait(100);
    d.getElementById('settings-button').click();const detail=d.getElementById('detail-toggle');detail.checked=true;detail.dispatchEvent(new w.Event('change'));
    assert(!d.body.classList.contains('immersive'),'Detailed text is available as an explicit opt-in');detail.checked=false;detail.dispatchEvent(new w.Event('change'));
    const motion=d.getElementById('motion-toggle');motion.checked=true;motion.dispatchEvent(new w.Event('change'));
    assert(d.body.classList.contains('reduced-motion'),'Reduced effects setting is applied');
    d.getElementById('settings-dialog').close();
    // World expansion and airship use the real production simulation, without saving.
    await wait(100);t.clearEnemies();x.setWeather('clear');t.step(3);
    const world=game.world,a=x.airship,at=a.test,as=()=>a.getState();
    const auto=d.getElementById('auto-weather');auto.checked=false;auto.dispatchEvent(new w.Event('change'));
    assert(Math.abs((world.size/3200)**2-6)<1e-10&&Math.abs((world.bounds/1430)**2-6)<1e-10,'Terrain and explorable area are exactly six times larger');
    assert(world.regions.length===8&&world.biomeAt(0,62).id==='meadow','Eight additional biomes preserve the starting meadow');
    assert(world.regions.every(r=>world.biomeAt(r.x,r.z).id===r.id&&x.getSceneryStats().counts[r.id]>250),'Every biome has its own region and hundreds of placed objects');
    assert(world.regions.every(r=>Number.isFinite(world.height(r.x,r.z)))&&world.height(0,-2450)>world.height(0,2450)+150,'Real snow mountains rise above the wetland terrain');
    assert(a.board(true)&&as().mode==='pilot','Touch boarding enters the airship cockpit');
    at.repair(true);at.step(12);at.repair(false);
    assert(as().deckWidth===13.6&&as().deckLength===60&&as().deckAreaRatio===4,'Walkable deck has four times its previous floor area');
    assert(as().interiorVisible&&!as().shellVisible,'Interior camera reveals the cabin and the view through its windows');
    at.setView();assert(as().shellVisible&&!as().interiorVisible&&!as().cutaway,'Exterior camera hides every interior mesh behind the opaque hull');
    at.setView();assert(as().interiorVisible&&!d.getElementById('airship-cutaway'),'Cutaway control cannot expose the interior from outside');
    const power=d.getElementById('airship-power');power.value='70';power.dispatchEvent(new w.Event('input'));
    assert(as().throttle===.7,'Touch thrust slider sets actual engine thrust');
    at.pose(2300,300,0,0);at.velocity(0,0,0);at.step(2,{mx:1,mz:0,running:false});
    assert(as().heading<-.1&&Math.hypot(...as().velocity)>5,'Steering turns the ship while maintained thrust moves it');
    d.getElementById('airship-stop').click();assert(as().throttle===0,'Stop control cuts thrust');
    at.velocity(0,0,0);at.pose(2300,300,0,0);
    const held=as();a.update(1,true);assert(as().position.join()===held.position.join()&&as().rooms[0].hp===held.rooms[0].hp,'Pause freezes flight and room damage');
    assert(a.interact()&&as().mode==='walk','Leaving the helm enables walking in the larger interior');
    at.look(0);
    for(let i=0;i<6;i++){
      const door=as().doors[i],side=door.side,sign=Math.sign(door.x)||1;
      const start=()=>at.local(side?door.x-sign*.5:0,0,side?door.z:door.z-.9);
      const controls={mx:side?sign:0,mz:side?0:1,running:false};
      start();at.door(i,false);at.step(.8);at.step(.5,controls);
      const blocked=as().local;
      assert(side?(blocked[0]-door.x)*sign<0:blocked[2]<door.z,'Closed door '+i+' blocks the walking capsule');
      start();at.door(i,true);at.step(.8);at.step(.65,controls);
      const crossed=as().local;
      assert(side?(crossed[0]-door.x)*sign>.2:crossed[2]>door.z+.2,'Open door '+i+' permits passage through the actual opening');
    }
    at.local(0,0,-10);at.door(0,false);at.step(1);
    assert(as().doors[0].open&&as().doors[0].t>.99,'Door reverses safely when the player occupies its closing path');
    at.local(0,0,-11.2);a.interact();at.step(1);
    assert(!as().doors[0].open&&as().doors[0].t===0,'Context interaction prioritizes the nearby door over the helm');
    at.pose(2400,300,0,0);at.lightning(5);at.lightning(5);at.step(.1);
    assert(as().rooms[5].hp<25&&as().rooms[5].exploded&&as().explosions>0,'Repeated lightning explodes and severely damages the engine room');
    at.local(1.35,0,10);at.repair(true);at.step(9);at.repair(false);
    assert(as().rooms[5].hp>99&&as().rooms[5].fire===0&&as().rooms[5].wet===0,'Holding repair restores the occupied room and extinguishes fire');
    a.test.forceExit();t.teleport(0,62);a.place();a.board(true);at.repair(true);at.step(12);at.repair(false);
    x.setWeather('rain');t.step(14);at.step(155);
    assert(as().rooms.some(r=>r.exploded)&&as().rooms.some(r=>r.hp<30),'Rain infiltration alone causes electrical faults, explosions and severe damage');
    x.setWeather('clear');t.step(5);at.repair(true);at.step(14);at.repair(false);
    assert(as().rooms.every(r=>r.hp>99&&r.fire===0),'Landed maintenance repairs every room without a soft lock');
    a.interact();at.local(-3.05,0,-2);at.door(6,false);at.step(1);
    assert(!a.exit(),'A closed boarding hatch prevents disembarking');
    at.door(6,true);at.step(1);at.pose(2300,300,0,0);at.step(.1);
    assert(!a.exit(),'An open hatch never permits unsafe midair disembarking');
    at.forceExit();t.teleport(0,62);a.place();a.board(true);a.interact();at.local(-3.05,0,-2);at.door(6,true);at.step(1);
    assert(a.exit()&&as().mode==='ground','Landed ship with an open hatch permits safe disembarking');
    assert(as().shellVisible&&!as().interiorVisible,'After disembarking the rounded opaque exterior remains visible');
    // Crafted scenery uses the same production batches and deterministic camera views.
    const stats=x.getSceneryStats(),views=x.getObjectViews();
    assert(['well','market','wagon','apiary','forge','shrine'].every(k=>stats.counts[k]===1),'All six handcrafted destinations exist exactly once');
    assert(stats.craftedInstances>6500&&stats.microInstances>400,'Thousands of modeled craft parts and micro-details are present');
    assert(stats.counts.pottery===100&&stats.counts.spokedWheels===4&&stats.counts.beehives===3,'Pottery, wagon wheels and beehives are fully assembled');
    assert(views.length===12&&new Set(views.map(v=>v.id)).size===12,'Twelve unique overview and detail compositions exist');
    assert(views.every(v=>v.eye.concat(v.target).every(Number.isFinite)),'Every camera composition contains finite coordinates');
    views[0].eye[0]=Infinity;assert(Number.isFinite(x.getObjectViews()[0].eye[0]),'Camera diagnostics return defensive copies');
    x.setSceneryDensity(1);const full=x.getSceneryStats();x.setSceneryDensity(.4);const light=x.getSceneryStats();
    assert(light.craftedInstances===full.craftedInstances&&light.microInstances===full.microInstances,'Density changes never remove structural craft parts');
    assert(light.activeInstances<full.activeInstances,'Density still reduces environmental vegetation');
    x.setSceneryDensity(NaN);assert(x.getSceneryStats().density===.4,'Nonfinite density input is safely ignored');
    t.teleport(-23,29);t.step(.3);assert(x.getSceneryStats().visibleMicroInstances>0,'Nearby crafted micro-detail becomes visible');
    t.teleport(1400,1400);t.step(.3);assert(x.getSceneryStats().visibleMicroInstances===0,'Distant micro-detail is actually culled');
    assert(x.sceneryClearance(-23,29)&&!x.sceneryClearance(1200,1200),'Grass clearance protects craft foundations only');
    assert(!game.test.setObjectView('missing-view'),'Invalid photo composition is rejected');
    assert(game.test.setObjectView('market-detail')&&game.getState().paused,'Selecting a real detail view pauses gameplay');
    assert(d.body.dataset.shot==='market-detail'&&game.getState().position.x===22,'Photo view moves to the actual market location');
    w.dispatchEvent(new w.Event('pagehide'));assert(localStorage.getItem('verdant-wildfront-v2')===save,'Object review leaves existing save data untouched');
    console.info('ALL '+passed+' WILDFRONT CHECKS PASSED');results.dataset.complete='true';
  }catch(e){console.error('WILDFRONT TEST FAILURE: '+e.message);results.dataset.complete='failed';results.textContent+='\nERROR '+e.message;}
})();
